{{- $searchPath := ":global.kolla.keystone.api.deployment:global.kolla.keystone.api.all:global.kolla.keystone.all:global.kolla.all" }}
{{- $c := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "contName" "keystone" }}
{{- $_ := set $c "imageName" "image_full" }}
{{- $_ := set $c "tagName" "image_tag" }}
{{- $imageFull := include "kolla_build_image_full" $c }}
{{- $resourceName := "keystone" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "keystone" }}
{{- $serviceType := "api" }}
{{- $configFileName := "keystone.conf" }}
{{- $configSectionName := "DEFAULT" }}
{{- $configListenHostParameter := "bind_host" }}
{{- $configListenPortParameter := "bind_port" }}
{{- $portName := "keystone-public" }}
{{- $extraConfigmapConfig := "keystone_extra_configmap_config" }}
{{- $extraVolumes := "keystone_extra_volumes" }}
{{- $extraVolumeMounts := "keystone_extra_volume_mounts" }}
{{- $extraAnnotations := "keystone_initcontainer" }}
{{- $checkPath := "/" }}
{{- $privileged := false }}
{{- $haproxy := false }}
{{- define "keystone_initcontainer" }}
pod.beta.kubernetes.io/init-containers: '[
{{- include "common_dependency_container_multi" . | indent 2 }}
  {
     "name": "initialize-keystone-logs",
     "image": "{{ .imageFull }}",
     "imagePullPolicy": "IfNotPresent",
     "command": [
         "sh",
         "-ce",
         "mkdir /var/log/kolla/keystone ;
          chown -R keystone: /var/log/kolla/keystone;
          chmod 755 /var/log/kolla/keystone; "],
     "volumeMounts": [
        {
           "name": "kolla-logs",
           "mountPath": "/var/log/kolla"
        }
     ]
  }
]'
{{- end }}
<<<<<<< HEAD
{{- define "keystone_extra_volumes" }}
- name: keystone-fernet-keys
  secret:
    secretName: keystone-fernet-keys
{{- end }}
{{- define "keystone_extra_volume_mounts" }}
- name: keystone-fernet-keys
  mountPath: /etc/keystone/fernet-keys
{{- end }}
{{- define "keystone_extra_configmap_config" }}
items:
- key: keystone.conf
  path: keystone.conf
- key: keystone-paste.ini
  path: keystone-paste.ini
- key: wsgi-keystone.conf
  path: wsgi-keystone.conf
- key: config.json
  path: config.json
{{- end }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "configFileName" $configFileName "configSectionName" $configSectionName "configListenHostParameter" $configListenHostParameter "configListenPortParameter" $configListenPortParameter "portName" $portName "imageFull" $imageFull "checkPath" $checkPath "extraConfigmapConfig" $extraConfigmapConfig "extraVolume" $extraVolumes "extraVolumeMounts" $extraVolumeMounts "extraAnnotations" $extraAnnotations "privileged" $privileged "haproxy" $haproxy "Values" .Values "Release" .Release "searchPath" $searchPath }}
=======
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "configFileName" $configFileName "configSectionName" $configSectionName "configListenHostParameter" $configListenHostParameter "configListenPortParameter" $configListenPortParameter "portName" $portName "imageFull" $imageFull "checkPath" $checkPath "extraAnnotations" $extraAnnotations "privileged" $privileged "haproxy" $haproxy "Values" .Values "Release" .Release "searchPath" $searchPath }}
>>>>>>> 6ab0755... Simple configmap to raw kubectl
{{- include "common_api_apache_deployment" $env }}
{{- end }}
