{{- $searchPath := ":global.kolla.nova.placement_api.create_keystone_endpoint.admin.job:global.kolla.nova.placement_api.create_keystone_endpoint.all:global.kolla.nova.placement_api.all:global.kolla.nova.all:global.kolla.all" }}
{{- $resourceName := "placement-create-keystone-endpoint-admin" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- $serviceName := "placement-api" }}
{{- $serviceType := "placement" }}
{{- $interface := "admin" }}
{{- $service := include "kolla_val_get_str" (dict "key" "service" "searchPath" $searchPath "Values" .Values) }}
{{- $port := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $placementapiAdminEndpointBuilt := printf "http://nova-%s:%s" $service $port }}
{{- $endpointURLFullUser := include "kolla_val_get_str" (dict "key" "endpoint" "searchPath" $searchPath "Values" .Values) }}
{{- $endpointURLFull := $endpointURLFullUser | default $placementapiAdminEndpointBuilt }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "interface" $interface "endpointURLFull" $endpointURLFull "Release" .Release "Values" .Values "searchPath" $searchPath }}
{{- include "common_create_keystone_endpoint" $env }}
{{- end }}
