apiVersion: v1
version: 0.7.0-1
description: rabbitmq service layer
name: rabbitmq
keywords:
  - openstack
  - rabbitmq
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
