dependencies:
  - name: rabbitmq-pv
    repository: http://localhost:10191
    version: 0.6.0-1
  - name: rabbitmq-pvc
    repository: http://localhost:10191
    version: 0.6.0-1
  - name: rabbitmq-svc
    repository: http://localhost:10191
    version: 0.6.0-1
  - name: rabbitmq-init-element-job
    repository: http://localhost:10191
    version: 0.6.0-1
  - name: rabbitmq-statefulset
    repository: http://localhost:10191
    version: 0.6.0-1
