name: ironic-api-create-db-job
version: 0.7.0-1
description: ironic api create db microservice package
keywords:
  - openstack
  - ironic
  - api
  - db
  - create
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
