apiVersion: v1
version: 0.7.0-1
description: openvswitch-vswitchd specific layer
name: openvswitch-vswitchd-daemonset
keywords:
  - openstack
  - openvswitch-vswitchd
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
