{{- $imageBuilt := printf "%s/%s/%s-%s-nova-api:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.image_tag }}
{{- $imageFull := .Values.image_full | default $imageBuilt }}
{{- $resourceName := "nova-api" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "nova" }}
{{- $serviceType := "api" }}
{{- $configFileName := "nova.conf" }}
{{- $configSectionName := "DEFAULT" }}
{{- $configListenHostParameter := "osapi_compute_listen" }}
{{- $configListenPortParameter := "osapi_compute_listen_port" }}
{{- $portName := "nova-api" }}
{{- $checkPath := "/healthcheck" }}
{{- $privileged := true }}
{{- $haproxy := .Values.haproxy | default true }}
{{- $extraVolumeMounts := "nova_api_extra_volume_mounts" }}
{{- define "nova_api_extra_volume_mounts" }}
- mountPath: /lib/modules
  name: lib-modules
{{- end }}
{{- $extraVolumes := "nova_api_extra_volumes" }}
{{- define "nova_api_extra_volumes" }}
- hostPath:
    path: /lib/modules
  name: lib-modules
{{- end }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "configFileName" $configFileName "configSectionName" $configSectionName "configListenHostParameter" $configListenHostParameter "configListenPortParameter" $configListenPortParameter "portName" $portName "imageFull" $imageFull "checkPath" $checkPath "extraVolumeMounts" $extraVolumeMounts "extraVolume" $extraVolumes "privileged" $privileged "haproxy" $haproxy "Values" .Values }}
{{- include "common_api_python_deployment" $env }}
{{- end }}
