apiVersion: v1
version: 0.7.0-1
description: rabbitmq-statefulset subservice layer
name: rabbitmq-statefulset
keywords:
  - openstack
  - rabbitmq
  - rabbitmq-pod
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
