{{- $elementSearchPath := ":global.kolla.elasticsearch.svc:global.kolla.elasticsearch.all:global.kolla.all:global" }}
{{- $elementName := include "kolla_val_get_str" (dict "key" "element_name" "searchPath" $elementSearchPath "Values" .Values ) }}
{{- $searchPath := printf ":global.kolla.%s.svc:global.kolla.%s.all:global.kolla.elasticsearch.svc:global.kolla.elasticsearch.all:global.kolla.all" $elementName $elementName }}
{{- $elementService := $elementName }}
{{- $localVals := dict }}
{{- $elementPort := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $c := dict "searchPath" $searchPath "key" "enabled" "retDict" $localVals "retKey" "enabled" "Values" .Values }}
{{- include "kolla_val_get_raw" $c }}
{{- with $env := dict "element_port" $elementPort "element_name" $elementName "element_service" $elementService "searchPath" $searchPath "Values" .Values "Release" .Release }}
{{- if $localVals.enabled }}
{{- include "common_svc" $env }}
{{- else }}
{{- include "common_disabled" (dict "elementName" $elementName "serviceKind" "svc") }}
{{- end }}
{{- end }}
