{{- $pvName := "mariadb" }}
{{- $storageProvider := .Values.storage_provider }}
{{- $storageProviderFStype := .Values.storage_provider_fstype | default "xfs" }}
{{- $volumeName := "mariadb"}}
{{- $volumeSizeGB := .Values.mariadb_volume_size_gb | default 10 }}
{{- with $env := dict "pvName" $pvName "storageProvider" $storageProvider "storageProviderFStype" $storageProviderFStype "volumeName" $volumeName "volumeSizeGB" $volumeSizeGB "Values" .Values }}
{{- include "common_pv" $env }}
{{- end }}
