global:
    kolla:
        all:
            kubernetes_entrypoint: true
        cinder:
            create_db:
                job:
                    dependencies:
                        service:
                        - mariadb
            manage_db:
                job:
                    dependencies:
                        service:
                        - mariadb
                        jobs:
                        - cinder-create-db
            create_keystone_user:
                job:
                    dependencies:
                        jobs:
                        - cinder-create-keystone-service
                        service:
                        - keystone-admin
            create_keystone_service:
                job:
                    dependencies:
                        service:
                        - keystone-admin
            create_keystone_servicev2:
                job:
                    dependencies:
                        service:
                        - keystone-admin
            create_keystone_endpoint:
                public:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-service
                            - cinder-create-keystone-user
                            - cinder-create-keystone-endpoint-internal
                            - cinder-create-keystone-endpoint-admin
                            service:
                            - keystone-admin
                internal:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-service
                            - cinder-create-keystone-user
                            - cinder-create-keystone-endpoint-admin
                            service:
                            - keystone-admin
                admin:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-service
                            - cinder-create-keystone-user
                            service:
                            - keystone-admin
                publicv2:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-servicev2
                            - cinder-create-keystone-user
                            - cinder-create-keystone-endpoint-internalv2
                            - cinder-create-keystone-endpoint-adminv2
                            service:
                            - keystone-admin
                internalv2:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-servicev2
                            - cinder-create-keystone-user
                            - cinder-create-keystone-endpoint-adminv2
                            service:
                            - keystone-admin
                adminv2:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-servicev2
                            - cinder-create-keystone-user
                            service:
                            - keystone-admin
                publicv3:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-servicev3
                            - cinder-create-keystone-user
                            - cinder-create-keystone-endpoint-internalv3
                            - cinder-create-keystone-endpoint-adminv3
                            service:
                            - keystone-admin
                internalv3:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-servicev3
                            - cinder-create-keystone-user
                            - cinder-create-keystone-endpoint-adminv3
                            service:
                            - keystone-admin
                adminv3:
                    job:
                        dependencies:
                            jobs:
                            - cinder-create-keystone-servicev3
                            - cinder-create-keystone-user
                            service:
                            - keystone-admin
            api:
                deployment:
                    dependencies:
                        jobs:
                        - cinder-create-keystone-endpoint-public
                        - cinder-create-keystone-endpoint-internal
                        - cinder-create-keystone-endpoint-admin
                        - cinder-create-keystone-endpoint-publicv2
                        - cinder-create-keystone-endpoint-internalv2
                        - cinder-create-keystone-endpoint-adminv2
                        - cinder-create-keystone-endpoint-publicv3
                        - cinder-create-keystone-endpoint-internalv3
                        - cinder-create-keystone-endpoint-adminv3
                        - cinder-create-db
                        - cinder-manage-db
                        service:
                        - mariadb
                        - keystone-admin
                svc:
                    port_external: true
            scheduler:
                statefulset:
                    dependencies:
                        jobs:
                        - cinder-create-keystone-endpoint-public
                        - cinder-create-keystone-endpoint-internal
                        - cinder-create-keystone-endpoint-admin
                        - cinder-create-keystone-endpoint-publicv2
                        - cinder-create-keystone-endpoint-internalv2
                        - cinder-create-keystone-endpoint-adminv2
                        - cinder-create-keystone-endpoint-publicv3
                        - cinder-create-keystone-endpoint-internalv3
                        - cinder-create-keystone-endpoint-adminv3
                        - cinder-create-db
                        - cinder-manage-db
                        service:
                        - cinder-api
