apiVersion: v1
version: 0.7.0-1
description: rabbitmq-pvc subservice layer
name: rabbitmq-pvc
keywords:
  - openstack
  - rabbitmq
  - rabbitmq-pvc
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
