apiVersion: v1
version: 0.7.0-1
description: mariadb service layer
name: mariadb
keywords:
  - openstack
  - mariadb
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
