dependencies:
  - name: mariadb-pv
    repository: http://localhost:10191
    version: 0.4.0-1
  - name: mariadb-pvc
    repository: http://localhost:10191
    version: 0.4.0-1
  - name: mariadb-svc
    repository: http://localhost:10191
    version: 0.4.0-1
  - name: mariadb-init-element-job
    repository: http://localhost:10191
    version: 0.4.0-1
  - name: mariadb-statefulset
    repository: http://localhost:10191
    version: 0.4.0-1
