{{- $searchPath := ":global.kolla.libvirt.pvc:global.kolla.libvirt.all:global.kolla.all" }}
{{- $pvcName := "libvirt" }}
{{- $storageProvider := include "kolla_val_get_str" (dict "key" "storage_provider" "searchPath" $searchPath "Values" .Values ) }}
{{- $volumeSizeGB := include "kolla_val_get_str" (dict "key" "size_gb" "searchPath" $searchPath "Values" .Values ) }}
{{- with $env := dict "pvcName" $pvcName "storageProvider" $storageProvider "volumeSizeGB" $volumeSizeGB "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_pvc" $env }}
{{- end }}
