apiVersion: v1
version: 0.7.0-1
description: mariadb-init-element subservice layer
name: mariadb-init-element-job
keywords:
  - openstack
  - mariadb
  - mariadb-init-element
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
