global:
    kolla:
        all:
            kubernetes_entrypoint: true
        keystone:
            create_db:
                job:
                    dependencies:
                        service:
                        - mariadb
            manage_db:
                job:
                    dependencies:
                        service:
                        - mariadb
                        jobs:
                        - keystone-create-db
            create_keystone_endpoints:
                job:
                    dependencies:
                        jobs:
                        - keystone-create-db
                        - keystone-manage-db
                        service:
                        - mariadb
                        - keystone-admin
                        - keystone-public
                        - keystone-internal
            api:
                deployment:
                    dependencies:
                        jobs:
                        - keystone-create-endpoints
                        - keystone-create-db
                        - keystone-manage-db
                        service:
                        - mariadb
                        - keystone-admin
                        - keystone-public
                        - keystone-internal
