global:
    kolla:
        all:
            kubernetes_entrypoint: true
        mariadb:
            all:
                enabled: false
                element_name: mariadb
        keystone:
            create_db:
                job:
                    dependencies:
                        service:
                        - mariadb
            manage_db:
                job:
                    dependencies:
                        service:
                        - mariadb
                        jobs:
                        - keystone-create-db
            create_keystone_endpoints:
                job:
                    dependencies:
                        service:
                        - mariadb
                        jobs:
                        - keystone-create-db
                        - keystone-manage-db
            api:
                deployment:
                    dependencies:
                        jobs:
                        - keystone-create-endpoints
                        - keystone-create-db
                        - keystone-manage-db
                        service:
                        - mariadb
