dependencies:
  - name: nova-delete-db-job
    repository: file://../../microservice/nova-delete-db-job
    version: 0.7.0-1
  - name: nova-api-delete-db-job
    repository: file://../../microservice/nova-api-delete-db-job
    version: 0.7.0-1
  - name: nova-cell0-delete-db-job
    repository: file://../../microservice/nova-cell0-delete-db-job
    version: 0.7.0-1
  - name: nova-delete-keystone-service-job
    repository: file://../../microservice/nova-delete-keystone-service-job
    version: 0.7.0-1
  - name: nova-delete-keystone-user-job
    repository: file://../../microservice/nova-delete-keystone-user-job
    version: 0.7.0-1
