dependencies:
  - name: nova-delete-db-job
    repository: http://localhost:10191
    version: 0.5.0-1
  - name: nova-api-delete-db-job
    repository: http://localhost:10191
    version: 0.5.0-1
  - name: nova-delete-keystone-service-job
    repository: http://localhost:10191
    version: 0.5.0-1
  - name: nova-delete-keystone-user-job
    repository: http://localhost:10191
    version: 0.5.0-1
