dependencies:
  - name: cinder-delete-db-job
    repository: file://../../microservice/cinder-delete-db-job
    version: 0.7.0-1
  - name: cinder-delete-keystone-service-job
    repository: file://../../microservice/cinder-delete-keystone-service-job
    version: 0.7.0-1
  - name: cinder-delete-keystone-servicev2-job
    repository: file://../../microservice/cinder-delete-keystone-servicev2-job
    version: 0.7.0-1
  - name: cinder-delete-keystone-user-job
    repository: file://../../microservice/cinder-delete-keystone-user-job
    version: 0.7.0-1
