apiVersion: v1
version: 0.7.0-1
description: tgtd microservice layer
name: tgtd-daemonset
keywords:
  - openstack
  - tgtd
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
