{{- $searchPath := ":global.kolla.nova.placement_api.create_keystone_user.job:global.kolla.nova.placement_api.create_keystone_user.all:global.kolla.nova.placement_api.all:global.nova.kolla.all:global.kolla.all" }}
{{- $resourceName := "nova-placement-api-create-keystone-user" }}
{{- $serviceName := "placement" }}
{{- $serviceType := "create-keystone-user" }}
{{- $elementName := .Values.element_name | default $serviceName }}
{{- $elementType := .Values.element_type | $serviceType }}

{{- $userName := include "kolla_val_get_str" (dict "key" "keystone_user_name" "searchPath" $searchPath "Values" .Values ) }}
{{- $userDomain := include "kolla_val_get_str" (dict "key" "keystone_user_domain" "searchPath" $searchPath "Values" .Values ) }}
{{- $userProject := include "kolla_val_get_str" (dict "key" "keystone_user_project" "searchPath" $searchPath "Values" .Values ) }}
{{- $userProjectDomain := include "kolla_val_get_str" (dict "key" "keystone_user_project_domain" "searchPath" $searchPath "Values" .Values ) }}
{{- $userRole := include "kolla_val_get_str" (dict "key" "keystone_user_role" "searchPath" $searchPath "Values" .Values ) }}

{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}

{{- with $env := dict "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "elementName" $elementName "elementType" $elementType "podTypeBootstrap" $podTypeBootstrap "userName" $userName "userDomain" $userDomain "userProject" $userProject "userProjectDomain" $userProjectDomain "userRole" $userRole "Values" .Values "Release" .Release "searchPath" $searchPath }}

{{- include "common_create_keystone_user" $env }}
{{- end }}
