{{- $searchPath := ":global.kolla.keystone.public.svc:global.kolla.keystone.public.all:global.kolla.keystone.all:global.kolla.all" }}
{{- $elementPort := include "kolla_val_get_str" (dict "key" "port" "searchPath" .searchPath "Values" .Values) }}
{{- $elementSuffix := .Values.element_compoenent | default "public" }}
{{- $elementServiceType := .Values.element_service_type | default "api" }}
{{- $elementService := .Values.element_service | default "keystone"  }}
{{- $elementNameComp := printf "%s-%s" $elementService $elementSuffix }}
{{- $elementName := .Values.element_name | default $elementNameComp }}
{{- with $env := dict "element_port" $elementPort "element_name" $elementName "element_service" $elementService "element_service_type" $elementServiceType "element_port_external" .Values.element_port_external "kolla_kubernetes_external_vip" .Values.kolla_kubernetes_external_vip "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_svc" $env }}
{{- end }}
