name: openstack-neutron
version: 2.0.2 #FIXME make this changable
description: FIXME
keywords:
  - openstack
  - neutron
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
