name: test-ceph-mon-daemonset
version: 0.7.0-1 #FIXME make this changable
description: ceph-mon daemon for kolla-kubernetes
keywords:
  - openstack
  - test
  - ceph
  - mon
  - daemon
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
