{{- $rabbitmqImageBuilt := printf "%s/%s/%s-%s-rabbitmq:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.rabbitmq_image_tag | default .Values.kolla_tag }}
{{- $rabbitmqImageFull := .Values.rabbitmq_image_full | default $rabbitmqImageBuilt }}
{{- $resourceName := "rabbitmq-bootstrap" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "Values" .Values "Release" .Release }}
apiVersion: batch/v1
kind: Job
spec:
  template:
{{- include "init_container_tail" $env | indent 4 }}
{{- include "common_dependency_container_single" | indent 10 }}
{{- include "init_container_tail" | indent 4 }}
    spec:
      nodeSelector:
          {{ .Values.selector_key }}: {{ .Values.selector_value | quote }}
      containers:
        - image: "{{ $rabbitmqImageFull }}"
          name: main
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
            - mountPath: {{ .Values.container_config_directory }}
              name: rabbitmq-config
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-persistent-storage
          env:
{{- include "common_bootstrap_env_vars" $env | indent 12 }}
            - name: RABBITMQ_CLUSTER_COOKIE
              value: {{ .Values.rabbitmq_cluster_cookie | quote }}
      volumes:
{{- include "common_volumes" $env | indent 8 }}
        - name: rabbitmq-config
          configMap:
            name: {{ .Values.element_name }}
        - name: rabbitmq-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.element_name }}
      restartPolicy: OnFailure
metadata:
  name: {{ .Values.element_name }}-bootstrap
{{- end }}
