name: nova-compute-ironic
version: 0.7.0-1
description: Helm chart for nova compute fronting ironic
keywords:
  - openstack
  - nova
  - compute
  - ironic
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
