name: keystone-fernet-setup-job
version: 0.7.0-1 #FIXME make this changable
description: keystone fernet token setup job
keywords:
  - openstack
  - keystone
  - fernet
  - setup
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
