{{- $restype := .Values.type }}
{{- $searchPath := printf ":global.kolla.neutron.l3_agent_%s.daemonset:global.kolla.neutron.l3_agent_%s.all:global.kolla.neutron.l3_agent.all:global.kolla.neutron.all:global.kolla.all" $restype $restype }}
{{- $c := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "contName" "neutron-l3-agent" }}
{{- $_ := set $c "imageName" "image_full" }}
{{- $_ := set $c "tagName" "image_tag" }}
{{- $imageFull := include "kolla_build_image_full" $c }}
{{- $localVals := dict }}
{{- $c1 := dict "key" "openvswitch_tcp" "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c1 "retDict" $localVals }}
{{- $_ := set $c1 "retKey" "openvswitch_tcp" }}
{{- $_ := include "kolla_val_get_raw" $c1 }}
{{- $c2 := dict "key" "dvr" "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c2 "retDict" $localVals }}
{{- $_ := set $c2 "retKey" "dvr" }}
{{- $_ := include "kolla_val_get_raw" $c2 }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" $searchPath "Values" .Values ) }}
{{- $containerConfigDirectory := include "kolla_val_get_str" (dict "key" "container_config_directory" "searchPath" $searchPath "Values" .Values ) }}
{{- $selectorKey := include "kolla_val_get_str" (dict "key" "selector_key" "searchPath" $searchPath "Values" .Values ) }}
{{- $selectorValue := include "kolla_val_get_str" (dict "key" "selector_value" "searchPath" $searchPath "Values" .Values ) }}
{{- $tunnelInterface := include "kolla_val_get_str" (dict "key" "tunnel_interface" "searchPath" $searchPath "Values" .Values ) }}
{{- $resourceName := printf "neutron-l3-agent-%s" $restype }}
{{- $netHostTrue := true }}
{{- $podTypeBootstrap := false }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" false "resourceName" $resourceName "Values" .Values "Release" .Release "searchPath" $searchPath }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-l3-agent-{{ $restype }}
  labels:
    component: neutron
    system: l3-agent-{{ $restype }}
spec:
  template:
    metadata:
      labels:
        component: neutron
        system: l3-agent-{{ $restype }}
    spec:
      hostNetwork: True
      hostIPC: True
      hostPID: True
      nodeSelector:
          {{ $selectorKey }}: {{ $selectorValue | quote }}
#FIXME Its unclear if ovsdb_connection, local_ip, and/or hostPID required. Try removing them once we have a working gate to test with.
      initContainers:
{{- include "common_dependency_container" $env | indent 8 }}
        - name: update-config
          image: {{ include "kolla_toolbox_image_full" . | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              cp -a /srv/configmap/..data/* /srv/pod-main-config/;
{{- if $localVals.openvswitch_tcp }}
              TUNNEL_INTERFACE={{ $tunnelInterface }};
              F=/var/lib/kolla-kubernetes/neutron-openvswitch-agent/tunnel_interface;
              [ -f $F ] && TUNNEL_INTERFACE=$(<$F);
              IP=$(ip addr list {{ $tunnelInterface }} | grep 'inet ' |cut -d' ' -f6|cut -d/ -f1);
              crudini --set /srv/pod-main-config/ml2_conf.ini ovs ovsdb_connection tcp:$IP:6640;
{{- end }}
              crudini --set /srv/pod-main-config/ml2_conf.ini ovs local_ip $IP;
{{- if eq $restype "compute" }}
              crudini --set /srv/pod-main-config/l3_agent.ini DEFAULT agent_mode dvr;
              crudini --set /srv/pod-main-config/l3_agent.ini DEFAULT handle_internal_only_routers false;
{{- else }}
              crudini --set /srv/pod-main-config/l3_agent.ini DEFAULT handle_internal_only_routers true;
{{- if $localVals.dvr }}
              crudini --set /srv/pod-main-config/l3_agent.ini DEFAULT agent_mode dvr_snat;
{{- else }}
              crudini --set /srv/pod-main-config/l3_agent.ini DEFAULT agent_mode legacy;
{{- end }}
{{- end }}
          volumeMounts:
            - name: neutron-l3-agent-configmap
              mountPath: /srv/configmap
            - name: pod-main-config
              mountPath: /srv/pod-main-config
        - name: update-permissions
          image: {{ $imageFull | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          securityContext:
            runAsUser: 0
          command:
            - /bin/sh
            - -c
            - |
              chown --recursive neutron.kolla /var/log/kolla;
              echo FIXME check for ip6tables loaded;
          volumeMounts:
            - name: kolla-logs
              mountPath: /var/log/kolla
      containers:
        - image: {{ $imageFull | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          name: main
          securityContext:
            privileged: true
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
{{- include "netns_volume_mounts" $env | indent 12 }}
            - mountPath: {{ $containerConfigDirectory }}
              name: pod-main-config
            - mountPath: /var/lib/neutron/kolla/
              name: neutron-metadata-socket
            - mountPath: /run
              name: host-run
              mountPropagation: Bidirectional
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
{{- include "common_containers" . | indent 8 }}
      volumes:
{{- include "common_volumes" . | indent 8 }}
{{- include "netns_volumes" . | indent 8 }}
        - name: pod-main-config
          emptyDir: {}
        - name: neutron-l3-agent-configmap
          configMap:
            name: neutron-l3-agent
            items:
            - key: neutron.conf
              path: neutron.conf
            - key: config.json
              path: config.json
            - key: ml2-conf.ini
              path: ml2_conf.ini
            - key: fwaas-driver.ini
              path: fwaas_driver.ini
            - key: l3-agent.ini
              path: l3_agent.ini
        - name: host-run
          hostPath:
            path: /run
        - name: neutron-metadata-socket
          hostPath:
            path: /var/lib/neutron/kolla/metadata_proxy
{{- end }}
