dependencies:
  - name: glance-delete-db-job
    repository: file://../../microservice/glance-delete-db-job
    version: 0.7.0-1
  - name: glance-delete-keystone-service-job
    repository: file://../../microservice/glance-delete-keystone-service-job
    version: 0.7.0-1
  - name: glance-delete-keystone-user-job
    repository: file://../../microservice/glance-delete-keystone-user-job
    version: 0.7.0-1
