apiVersion: v1
version: 0.7.0-1
description: rabbitmq-pv subservice layer
name: rabbitmq-pv
keywords:
  - openstack
  - rabbitmq
  - rabbitmq-pv
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
