{{- $searchPath := ":global.kolla.cinder.create_keystone_endpoint.internalv3.job:global.kolla.cinder.create_keystone_endpoint.all:global.kolla.cinder.api.all:global.kolla.cinder.all:global.kolla.all" }}
{{- $resourceName := "cinder-create-keystone-endpoint-internalv3" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- $serviceName := "cinder" }}
{{- $serviceType := "volume" }}
{{- $interface := "internal" }}
{{- $service := include "kolla_val_get_str" (dict "key" "service" "searchPath" $searchPath "Values" .Values) }}
{{- $port := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $cinderInternalEndpointBuilt := printf "http://%s:%s/v3/%%(tenant_id)s" $service $port }}
{{- $endpointURLFullUser := include "kolla_val_get_str" (dict "key" "endpoint" "searchPath" $searchPath "Values" .Values) }}
{{- $endpointURLFull := $endpointURLFullUser | default $cinderInternalEndpointBuilt }}
{{- $postfix := "v3" }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "interface" $interface "endpointURLFull" $endpointURLFull "postfix" $postfix "Release" .Release "Values" .Values "searchPath" $searchPath }}
{{- include "common_create_keystone_endpoint" $env }}
{{- end }}
