{{- $searchPath := ":global.kolla.nova.cell0.delete_db.job:global.kolla.nova.cell0.delete_db.all:global.kolla.nova.cell0.all:global.kolla.nova.all:global.kolla.all" }}
{{- $resourceName := "nova-cell0" }}
{{- $serviceName := "nova" }}
{{- $podTypeBootstrap := true }}
{{- with $env := dict "resourceName" $resourceName "serviceName" $serviceName "podTypeBootstrap" $podTypeBootstrap "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_delete_db_job" $env }}
{{- end }}
