{{- $imageBuilt := printf "%s/%s/%s-%s-keystone:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.image_tag }}
{{- $imageFull := .Values.image_full | default $imageBuilt }}
{{- $resourceName := "keystone" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "keystone" }}
{{- $serviceType := "api" }}
{{- $configFileName := "keystone.conf" }}
{{- $configSectionName := "DEFAULT" }}
{{- $configListenHostParameter := "bind_host" }}
{{- $configListenPortParameter := "bind_port" }}
{{- $portName := "keystone-public" }}
{{- $extraConfigmapConfig := "keystone_extra_configmap_config" }}
{{- $checkPath := "/" }}
{{- $privileged := false }}
{{- $haproxy := false }}
{{- define "keystone_extra_configmap_config" }}
items:
- key: keystone.conf
  path: keystone.conf
- key: keystone-paste.ini
  path: keystone-paste.ini
- key: wsgi-keystone.conf
  path: wsgi-keystone.conf
- key: config.json
  path: config.json
{{- end }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "configFileName" $configFileName "configSectionName" $configSectionName "configListenHostParameter" $configListenHostParameter "configListenPortParameter" $configListenPortParameter "portName" $portName "imageFull" $imageFull "checkPath" $checkPath "extraConfigmapConfig" $extraConfigmapConfig "privileged" $privileged "haproxy" $haproxy "Values" .Values }}
{{- include "common_api_apache_deployment" $env }}
{{- end }}
