{{- define "common_statefulset" }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" .searchPath "Values" .Values ) }}
{{- $containerConfigDirectory := include "kolla_val_get_str" (dict "key" "container_config_directory" "searchPath" .searchPath "Values" .Values ) }}
{{- $selectorKey := include "kolla_val_get_str" (dict "key" "selector_key" "searchPath" .searchPath "Values" .Values ) }}
{{- $selectorValue := include "kolla_val_get_str" (dict "key" "selector_value" "searchPath" .searchPath "Values" .Values ) }}
{{- $replicas := include "kolla_val_get_str" (dict "key" "replicas" "searchPath" .searchPath "Values" .Values ) }}
apiVersion: apps/v1beta1
kind: StatefulSet
spec:
  serviceName: {{ .serviceName | quote }}
  replicas: {{ $replicas }}
  template:
    metadata:
      labels:
        service: {{ .serviceName }}
        type: {{ .serviceType }}
    spec:
      nodeSelector:
          {{ $selectorKey }}: {{ $selectorValue | quote }}
      init-containers:
{{- include "common_dependency_container" . | indent 8 }}
        - name: initialize-config
          image: {{ include "kolla_toolbox_image_full" . | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          command:
            - /bin/sh
            - -ce
            - cp -a /config/..data/* /podconfig/;
          volumeMounts:
            - name: service-config
              mountPath: /config/
            - name: pod-config
              mountPath: /podconfig/
      containers:
        - name: main
          image: "{{ .imageFull }}"
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          volumeMounts:
{{- include "common_volume_mounts" . | indent 12 }}
            - mountPath: {{ $containerConfigDirectory }}
              name: pod-config
          env:
{{- include "common_env_vars" . | indent 12 }}
{{- if .privileged }}
          securityContext:
            privileged: true
{{- end }}
{{- include "common_containers" . | indent 8 }}
      volumes:
{{- include "common_volumes" . | indent 8 }}
        - name: service-config
          configMap:
            name: {{ .serviceName }}-{{ .serviceType }}
        - name: pod-config
          emptyDir: {}
metadata:
   name: {{ .serviceName }}-{{ .serviceType }}
{{- end }}
