{{- define "common_delete_keystone_user" }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" .searchPath "Values" .Values ) }}
{{- $region := include "kolla_val_get_str" (dict "key" "region" "searchPath" .searchPath "Values" .Values ) }}
{{- $selectorKey := include "kolla_val_get_str" (dict "key" "selector_key" "searchPath" .searchPath "Values" .Values ) }}
{{- $selectorValue := include "kolla_val_get_str" (dict "key" "selector_value" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminProtocol := include "kolla_val_get_str" (dict "key" "keystone_admin_protocol" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminSvcname := include "kolla_val_get_str" (dict "key" "keystone_admin_svcname" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminPort := include "kolla_val_get_str" (dict "key" "keystone_admin_port" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminProject := include "kolla_val_get_str" (dict "key" "keystone_admin_project" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminProjectDomainName := include "kolla_val_get_str" (dict "key" "keystone_admin_project_domain_name" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminDomainName := include "kolla_val_get_str" (dict "key" "keystone_admin_domain_name" "searchPath" .searchPath "Values" .Values ) }}
{{- $keystoneAdminUserName := include "kolla_val_get_str" (dict "key" "keystone_admin_username" "searchPath" .searchPath "Values" .Values ) }}
{{- $authURLBuilt := printf "%s://%s:%s" $keystoneAdminProtocol $keystoneAdminSvcname $keystoneAdminPort }}
{{- $authURLUser := include "kolla_val_get_str" (dict "key" "keystone_admin_url" "searchPath" .searchPath "Values" .Values ) }}
{{- $authURLFull := $authURLUser | default $authURLBuilt }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .serviceName }}-delete-keystone-user"
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      nodeSelector:
          {{ $selectorKey }}: {{ $selectorValue | quote }}
      init-containers:
{{- include "common_dependency_container" . | indent 8 }}
      containers:
        - image: {{ include "kolla_toolbox_image_full" . | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          name: main
          command: ["sh", "-xec"]
          args:
            - |
                /usr/bin/openstack user delete --domain {{ .userDomain }} {{ .userName }};
          volumeMounts:
{{ include "common_volume_mounts" . | indent 12 }}
          env:
            - name: OS_USERNAME
              value: {{ $keystoneAdminUserName | quote }}
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_REGION_NAME
              value: {{ $region | quote }}
            - name: OS_PROJECT_NAME
              value: {{ $keystoneAdminProject | quote }}
            - name: OS_AUTH_URL
              value: {{ $authURLFull | quote }}
            - name: OS_PROJECT_DOMAIN_NAME
              value: {{ $keystoneAdminProjectDomainName | default $keystoneAdminDomainName }}
            - name: OS_USER_DOMAIN_NAME
              value: {{ $keystoneAdminDomainName | default $keystoneAdminDomainName }}
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keystone-admin-password
                  key: password
            - name: KEYSTONE_PASSWORD
              valueFrom:
               secretKeyRef:
                  name: {{ .serviceName }}-keystone-password
                  key: password
      volumes:
{{ include "common_volumes" . | indent 8 }}
      restartPolicy: OnFailure
{{- end }}
