{{- define "common_delete_db_job" }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" .searchPath "Values" .Values ) }}
{{- $containerConfigDirectory := include "kolla_val_get_str" (dict "key" "container_config_directory" "searchPath" .searchPath "Values" .Values ) }}
{{- $selectorKey := include "kolla_val_get_str" (dict "key" "selector_key" "searchPath" .searchPath "Values" .Values ) }}
{{- $selectorValue := include "kolla_val_get_str" (dict "key" "selector_value" "searchPath" .searchPath "Values" .Values ) }}
{{- $databaseHost := include "kolla_val_get_str" (dict "key" "database_host" "searchPath" .searchPath "Values" .Values ) }}
{{- $databasePort := include "kolla_val_get_str" (dict "key" "database_port" "searchPath" .searchPath "Values" .Values ) }}
{{- $databaseName := include "kolla_val_get_str" (dict "key" "database_name" "searchPath" .searchPath "Values" .Values ) }}
{{- $databaseUser := include "kolla_val_get_str" (dict "key" "database_user" "searchPath" .searchPath "Values" .Values ) }}
{{ $serviceNameUpper := .serviceName | upper | replace "-" "_" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .resourceName }}-delete-db"
spec:
  template:
    spec:
      nodeSelector:
          {{ $selectorKey }}: {{ $selectorValue | quote }}
      restartPolicy: OnFailure
      initContainers:
{{- include "common_dependency_container" . | indent 8 }}
      containers:
        - image: {{ include "kolla_toolbox_image_full" . | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          name: "deleting-{{ .serviceName }}-database"
          command: ["sh", "-c"]
          args:
            - ansible localhost -m mysql_db -a
              "login_host='{{ $databaseHost }}'
               login_port='{{ $databasePort }}'
               login_user='root'
               login_password='$DATABASE_PASSWORD'
               name='{{ $databaseName }}'
               state='absent'"
          volumeMounts:
{{ include "common_volume_mounts" . | indent 12 }}
          env:
            - name: ANSIBLE_NOCOLOR
              value: "1"
            - name: ANSIBLE_LIBRARY
              value: "/usr/share/ansible"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: password
        - image: {{ include "kolla_toolbox_image_full" . | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          name: "deleting-{{ .serviceName }}-user"
          command: ["sh", "-c"]
          args:
            - ansible localhost -m mysql_user -a
              "login_host='{{ $databaseHost }}'
               login_port='{{ $databasePort }}'
               login_user='root'
               login_password='$DATABASE_PASSWORD'
               name='{{ $databaseUser }}'
               state='absent'"
          volumeMounts:
{{ include "common_volume_mounts" . | indent 12 }}
          env:
            - name: ANSIBLE_NOCOLOR
              value: "1"
            - name: ANSIBLE_LIBRARY
              value: "/usr/share/ansible"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: password
            - name: "{{ $serviceNameUpper }}_DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ .serviceName }}-database-password"
                  key: password
      volumes:
{{- include "common_volumes" . | indent 8 }}
{{- end }}
