{{- define "common_pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvcName }}
{{- if eq .storageProvider "aws" }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: experimental_can_be_anything_in_kubernetes_1_2
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .volumeSizeGB }}Gi
{{- end }}
