{{- define "common_pv" }}
{{- $cephPool := include "kolla_val_get_str" (dict "key" "ceph.pool" "searchPath" .searchPath "Values" .Values) }}
{{- $cephUser := include "kolla_val_get_str" (dict "key" "ceph.user" "searchPath" .searchPath "Values" .Values) }}
{{- $cephKeyring := include "kolla_val_get_str" (dict "key" "ceph.keyring" "searchPath" .searchPath "Values" .Values) }}
{{- $cephSecretName := include "kolla_val_get_str" (dict "key" "ceph.secret_name" "searchPath" .searchPath "Values" .Values) }}
{{- $localVals := dict }}
{{- $c := dict "searchPath" .searchPath "Values" .Values }}
{{- $_ := set $c "key" "ceph.monitors" }}
{{- $_ := set $c "retDict" $localVals }}
{{- $_ := set $c "retKey" "monitors" }}
{{- $_ := include "kolla_val_get_raw" $c }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .pvName }}
spec:
  accessModes:
    - ReadWriteOnce
  labels:
    app: {{ .pvName }}
  capacity:
    storage: {{ .volumeSizeGB }}Gi
{{- if eq .storageProvider "host" }}
  hostPath:
    path: /var/lib/kolla/volumes/{{ .pvName }}

{{- else if eq .storageProvider "gce" }}
  gcePersistentDisk:
    pdName: {{ .pvName }}
    fsType: {{ .storageProviderFStype | default "xfs" }}

{{- else if eq .storageProvider "ceph" }}
  rbd:
    monitors:
      {{- range $localVals.monitors }}
      - {{ if contains ":" . }} {{ . | quote}} {{ else }} {{ printf "%s:6789" . | quote }} {{ end }}
      {{- end }}
    pool: {{ $cephPool }}
    image: {{ .volumeName }}
    user: {{ $cephUser }}
    {{- if $cephKeyring }}
    {{- if gt ($cephKeyring | len) 0 }}
    keyring: {{ $cephKeyring }}
    {{- end }}
    {{- end }}
    {{- if $cephSecretName }}
    {{- if gt ($cephSecretName | len) 0 }}
    secretRef:
      name: {{ $cephSecretName }}
    {{- end }}
    {{- end }}
    fsType: {{ .storageProviderFStype }}
    readOnly: false
{{- end }}
{{- end }}
