{{- $elementPort := .Values.rabbitmq_port | default 5672 }}
{{- $elementName := .Values.element_name }}
{{- $elementService := .Values.element_name }}
{{- with $env := dict "element_port" $elementPort "element_name" $elementName "element_service" $elementService "Values" .Values }}
{{- include "common_svc" $env }}
{{- end }}
