{{- $searchPath := ":global.kolla.keystone.create_keystone_endpoints.job:global.kolla.keystone.create_keystone_endpoints.all:global.kolla.keystone.all:global.kolla.all" }}
{{- $containerConfigDirectory := include "kolla_val_get_str" (dict "key" "container_config_directory" "searchPath" $searchPath "Values" .Values ) }}
{{- $selectorKey := include "kolla_val_get_str" (dict "key" "selector_key" "searchPath" $searchPath "Values" .Values ) }}
{{- $selectorValue := include "kolla_val_get_str" (dict "key" "selector_value" "searchPath" $searchPath "Values" .Values ) }}
{{- $port := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values ) }}
{{- $adminPort := include "kolla_val_get_str" (dict "key" "admin_port" "searchPath" $searchPath "Values" .Values ) }}
{{- $localVals := dict }}
{{- $c := dict "key" "admin_port_external" "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "retDict" $localVals }}
{{- $_ := set $c "retKey" "admin_port_external" }}
{{- $_ := include "kolla_val_get_raw" $c }}
{{- $adminPortExternal := $localVals.admin_port_external }}
{{- $region := include "kolla_val_get_str" (dict "key" "region" "searchPath" $searchPath "Values" .Values ) }}
{{- $c := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "contName" "keystone" }}
{{- $_ := set $c "imageName" "image_full" }}
{{- $_ := set $c "tagName" "image_tag" }}
{{- $imageFull := include "kolla_build_image_full" $c }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" $searchPath "Values" .Values ) }}
{{- $resourceName := "keystone" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- $elementName := include "kolla_val_get_str" (dict "key" "element_name" "searchPath" $searchPath "Values" .Values ) | default $resourceName }}
{{- $defaultPublicDnsName := printf "%s-public" $elementName }}
{{- $defaultAdminDnsName := printf "%s-admin" $elementName }}
{{- $userDnsName := include "kolla_val_get_str" (dict "key" "dns_name" "searchPath" $searchPath "Values" .Values ) }}
{{- $publicDnsName := $userDnsName | default $defaultPublicDnsName }}
{{- $adminDnsName := $userDnsName | default $defaultAdminDnsName }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "Values" .Values "Release" .Release "searchPath" $searchPath }}
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-create-endpoints
spec:
  template:
{{- include "init_container_header" $env | indent 4 }}
{{- include "common_dependency_container_single" $env | indent 10 }}
{{- include "init_container_tail" $env | indent 4 }}
    spec:
      nodeSelector:
          {{ $selectorKey }}: {{ $selectorValue | quote }}
      restartPolicy: OnFailure
      containers:
        - image: "{{ $imageFull }}"
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          name: main
          command: ["sh", "-c", "mkdir -p /var/log/kolla/keystone; sudo -E kolla_set_configs;
                    kolla_keystone_bootstrap admin
                    $KEYSTONE_ADMIN_PASSWORD
                    admin
                    admin
{{- if $adminPortExternal }}
                    http://{{ $adminDnsName }}:{{ $adminPort }}
{{- else }}
                    http://{{ $elementName }}-admin:{{ $adminPort }}
{{- end }}
                    http://{{ $elementName }}-internal:{{ $port }}
                    http://{{ $publicDnsName }}:{{ $port }}
                    {{ $region }}"]
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
            - mountPath: {{ $containerConfigDirectory }}
              name: service-configmap
              readOnly: true
            - name: keystone-fernet-keys
              mountPath: /etc/keystone/fernet-keys
          env:
            - name: KOLLA_KUBERNETES
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ONCE"
            - name: KEYSTONE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keystone-admin-password
                  key: password
      volumes:
{{- include "common_volumes" . | indent 8 }}
        - name: service-configmap
          configMap:
            name: {{ .resourceName }}
        - name: keystone-fernet-keys
          secret:
            secretName: keystone-fernet-keys
{{- end }}
