apiVersion: v1
version: 0.7.0-1
description: iscsid microservice layer
name: iscsid-daemonset
keywords:
  - openstack
  - iscsid
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
