{{- $searchPath := ":global.kolla.heat.api_cfn.deployment:global.kolla.heat.api_cfn.all:global.kolla.heat.all:global.kolla.all" }}
{{- $c := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "contName" "heat-api-cfn" }}
{{- $_ := set $c "imageName" "image_full" }}
{{- $_ := set $c "tagName" "image_tag" }}
{{- $imageFull := include "kolla_build_image_full" $c }}
{{- $resourceName := "heat-api-cfn" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "heat-cfn" }}
{{- $serviceType := "api" }}
{{- $configFileName := "heat.conf" }}
{{- $configSectionName := "heat_api_cfn" }}
{{- $configListenHostParameter := "bind_host" }}
{{- $configListenPortParameter := "bind_port" }}
{{- $portName := "heat-api-cfn" }}
{{- $checkPath := "/" }}
{{- $extraConfigmapConfig := "heat_api_cfn_extra_configmap_config" }}
{{- $privileged := false }}
{{- define "heat_api_cfn_extra_configmap_config" }}
items:
- key: heat.conf
  path: heat.conf
- key: policy.json
  path: policy.json
- key: api-paste.ini
  path: api-paste.ini
- key: AWS_CloudWatch_Alarm.yaml
  path: templates/AWS_CloudWatch_Alarm.yaml
- key: AWS_RDS_DBInstance.yaml
  path: templates/AWS_RDS_DBInstance.yaml
- key: config.json
  path: config.json
{{- end }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "configFileName" $configFileName "configSectionName" $configSectionName "configListenHostParameter" $configListenHostParameter "configListenPortParameter" $configListenPortParameter "portName" $portName "imageFull" $imageFull "checkPath" $checkPath "extraConfigmapConfig" $extraConfigmapConfig "privileged" $privileged "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_api_python_deployment" $env }}
{{- end }}
