name: test-ceph-init-osd-job
version: 0.7.0-1 #FIXME make this changable
description: ceph-init-osd job for kolla-kubernetes
keywords:
  - openstack
  - test
  - ceph
  - osd
  - initial
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
