{{- $searchPath := ":global.kolla.ironic.api.svc:global.kolla.ironic.api.all:global.kolla.ironic.all:global.kolla.all" }}
{{- $elementPort := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $rootElementName := .Values.element_name | default "ironic" }}
{{- $elementServiceType := .Values.element_service_type | default "api" }}
{{- $elementService := $rootElementName }}
{{- $elementName := printf "%s-%s" $elementService $elementServiceType }}
{{- $localVals := dict "nodePort" "node_port" }}
{{- $_ := set $localVals "nodePortEnabled" "node_port_enabled" }}
{{- $_ := set $localVals "portExternal" "port_external" }}
{{- $_ := set $localVals "ironicProvision" "ironic_provision" }}
{{- $c1 := dict "key" $localVals.nodePortEnabled "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c1 "retDict" $localVals }}
{{- $_ := set $c1 "retKey" "node_port_enabled" }}
{{- $_ := include "kolla_val_get_raw" $c1 }}
{{- $c2 := dict "key" $localVals.portExternal "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c2 "retDict" $localVals }}
{{- $_ := set $c2 "retKey" "port_external" }}
{{- $_ := include "kolla_val_get_raw" $c2 }}
{{- $c3 := dict "key" $localVals.ironicProvision "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c3 "retDict" $localVals }}
{{- $_ := set $c3 "retKey" "ironic_provision" }}
{{- $_ := include "kolla_val_get_raw" $c3 }}
{{- $c4 := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c1 "key" "ironic_conductor_ips" }}
{{- $_ := set $c1 "retDict" $localVals }}
{{- $_ := set $c1 "retKey" "ironic_conductor_ips" }}
{{- $_ := include "kolla_val_get_raw" $c1 }}
{{- $nodePort := include "kolla_val_get_str" (dict "key" $localVals.nodePort "searchPath" $searchPath "Values" .Values) }}
{{- $externalVip := include "kolla_val_get_str" (dict "key" "external_vip" "searchPath" $searchPath "Values" .Values) }}
apiVersion: v1
kind: Service
spec:
  ports:
    - port: {{ $elementPort }}
      name: {{ $elementName | quote }}
{{- if $localVals.node_port_enabled }}
      nodePort: {{ $nodePort }}
  type: NodePort
{{- else if  $localVals.port_external }}
  externalIPs:
{{- if $localVals.ironic_provision }}
{{- range $localVals.ironic_conductor_ips }}
    - {{ . }}
{{- end }}
{{- end }}
    - {{ $externalVip }}
{{- end }}
  selector:
    service: {{ $elementService | quote }}
{{- if $elementServiceType }}
    type: {{ $elementServiceType | quote }}
{{- end }}
metadata:
   name:  {{ $elementName | quote }}
