{{- $imageBuilt := printf "%s/%s/%s-%s-cinder-scheduler:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.image_tag }}
{{- $imageFull := .Values.image_full | default $imageBuilt }}
{{- $resourceName := "heat-engine" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "heat" }}
{{- $serviceType := "engine" }}
{{- $privileged := "true" }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "imageFull" $imageFull "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "privileged" $privileged "Values" .Values }}
{{- include "common_statefulset" $env }}
{{- end }}
