apiVersion: v1
version: 0.0.1
description: openvswitch-ovsdb specific layer
name: openvswitch-ovsdb
keywords:
  - openstack
  - openvswitch-ovsdb
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
