apiVersion: v1
version: 0.7.0-1
description: openvswitch service layer
name: openvswitch
keywords:
  - openstack
  - openvswitch-ovsdb
  - openvswitch-vswitchd
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
