dependencies:
  - name: openvswitch-ovsdb-daemonset
    repository: http://localhost:10191
    version: 0.4.0-1
  - name: openvswitch-vswitchd-daemonset
    repository: http://localhost:10191
    version: 0.4.0-1
