name: cinder-create-keystone-endpoint-internalv2
version: 3.0.0-1 #FIXME make this changable
description: Helm chart for the cinder keystone v2 internal endpoint 
keywords:
  - openstack
  - cinder
  - keystone-endpoint-internal
  - v2
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready

