name: glance-registry-deployment
version: 0.7.0-1
description: Helm chart for the glance registry
keywords:
  - openstack
  - glance
  - registry
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
