svc_name: registry
node_port: 30400
initial_load: false
replicas: 1
distro: centos
type: source
branch: master
init_image: centos
init_image_version: latest
registry_image: registry
registry_image_version: 2
tarball_url: http://tarballs.openstack.org/kolla/images/
