name: cinder-scheduler-statefulset
version: 0.7.0-1
description: Helm chart for cinder scheduler pod
keywords:
  - openstack
  - cinder
  - cinder-scheduler
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
