name: heat-create-keystone-endpoint-public-job
version: 0.7.0-1 #FIXME make this changable
description: Helm chart for creating heat public keystone endpoint
keywords:
  - openstack
  - heat
  - keystone-endpoint-public
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
