{{- $searchPath := ":global.kolla.glance.registry.svc:global.kolla.glance.registry.all:global.kolla.glance.all:global.kolla.all" }}
{{- $elementPort := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $elementService := "glance" }}
{{- $elementName := printf "%s-registry" $elementService }}
{{- $elementType := "registry" }}
{{- with $env := dict "element_port" $elementPort "element_name" $elementName "element_service" $elementService "element_service_type" $elementType "Values" .Values "Release" .Release "searchPath" $searchPath "tls" 1 }}
{{- include "common_svc" $env }}
{{- end }}
