{{- $searchPath := ":global.kolla.heat.api_cfn.create_keystone_endpoint.admin.job:global.kolla.heat.api_cfn.create_keystone_endpoint.all:global.kolla.heat.api_cfn.all:global.kolla.heat.all:global.kolla.all" }}
{{- $resourceName := "heat-cfn-create-keystone-endpoint-admin" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- $serviceName := "heat-cfn" }}
{{- $serviceType := "cloudformation" }}
{{- $interface := "admin" }}
{{- $service := include "kolla_val_get_str" (dict "key" "service" "searchPath" $searchPath "Values" .Values) }}
{{- $port := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $heatCfnAdminEndpointBuilt := printf "http://%s:%s/v1" $service $port }}
{{- $endpointURLFullUser := include "kolla_val_get_str" (dict "key" "endpoint" "searchPath" $searchPath "Values" .Values) }}
{{- $endpointURLFull := $endpointURLFullUser | default $heatCfnAdminEndpointBuilt }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "interface" $interface "endpointURLFull" $endpointURLFull "Release" .Release "Values" .Values "searchPath" $searchPath }}
{{- include "common_create_keystone_endpoint" $env }}
{{- end }}
