{{- $searchPath := ":global.kolla.glance.manage_db.job:global.kolla.glance.manage_db.all:global.kolla.glance.api.all:global.kolla.glance.all:global.kolla.all" }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" $searchPath "Values" .Values ) }}
{{- $containerConfigDirectory := include "kolla_val_get_str" (dict "key" "container_config_directory" "searchPath" $searchPath "Values" .Values ) }}
{{- $selectorKey := include "kolla_val_get_str" (dict "key" "selector_key" "searchPath" $searchPath "Values" .Values ) }}
{{- $selectorValue := include "kolla_val_get_str" (dict "key" "selector_value" "searchPath" $searchPath "Values" .Values ) }}
{{- $pvcName := include "kolla_val_get_str" (dict "key" "pvc_name" "searchPath" $searchPath "Values" .Values ) }}
{{- $c := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "contName" "glance-api" }}
{{- $_ := set $c "imageName" "image_full" }}
{{- $_ := set $c "tagName" "image_tag" }}
{{- $imageFull := include "kolla_build_image_full" $c }}
{{- $localVals := dict }}
{{- $c1 := dict "key" "ceph_backend" "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c1 "retDict" $localVals }}
{{- $_ := set $c1 "retKey" "ceph_backend" }}
{{- $_ := include "kolla_val_get_raw" $c1 }}
{{- $resourceName := "glance" }}
{{- $serviceName := "glance-api" }}
{{- $podTypeBootstrap := true }}
{{- with $env := dict "resourceName" $resourceName "serviceName" $serviceName "podTypeBootstrap" $podTypeBootstrap "imageFull" $imageFull "Values" .Values "Release" .Release "searchPath" $searchPath }}
apiVersion: batch/v1
kind: Job
metadata:
  name: glance-manage-db
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
          {{ $selectorKey }}: {{ $selectorValue | quote }}
      initContainers:
{{- include "common_dependency_container" . | indent 8 }}
      containers:
        - image: {{ $imageFull | quote }}
          imagePullPolicy: {{ $imagePullPolicy | quote }}
          name: main
          env:
{{- include "common_bootstrap_env_vars" $env | indent 12 }}
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
{{- if not $localVals.ceph_backend  }}
            - mountPath: {{ $containerConfigDirectory }}
              name: glance-api-config
              readOnly: true
            - mountPath: /var/lib/glance/
              name: glance-persistent-storage
{{- else }}
            - mountPath: {{ $containerConfigDirectory }}/config.json
              name: glance-api-config
              readOnly: true
              subPath: config.json
            - mountPath: {{ $containerConfigDirectory }}/glance-api.conf
              name: glance-api-config
              readOnly: true
              subPath: glance-api.conf
            - mountPath: {{ $containerConfigDirectory }}/ceph.conf
              name: ceph-conf
              subPath: ceph.conf
            - mountPath: {{ $containerConfigDirectory }}/ceph.client.glance.keyring
              name: ceph-conf
              subPath: ceph.conf
{{- end }}
      volumes:
{{- include "common_volumes" $env | indent 8 }}
        - name: glance-api-config
          configMap:
            name: glance-api
{{- if not $localVals.ceph_backend }}
        - name: glance-persistent-storage
          persistentVolumeClaim:
            claimName: {{ $pvcName }}
{{- else }}
        - name: ceph-conf
          configMap:
            name: ceph-conf
{{- end }}
{{- end }}
