{{- $pvName := .Values.pv_name | default "glance" }}
{{- $storageProvider := .Values.storage_provider }}
{{- $storageProviderFStype := .Values.storage_provider_fstype | default "xfs" }}
{{- $volumeName := .Values.pv_name | default "glance" }}
{{- $volumeSizeGB := .Values.glance_volume_size_gb | default 10 }}
{{- with $env := dict "pvName" $pvName "storageProvider" $storageProvider "storageProviderFStype" $storageProviderFStype "volumeName" $volumeName "volumeSizeGB" $volumeSizeGB "Values" .Values }}
{{- include "common_pv" $env }}
{{- end }}
