name: neutron-l3-agent-daemonset
version: 0.7.0-1 #FIXME make this changable
description: FIXME
keywords:
  - openstack
  - neutron
  - l3-agent
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
