apiVersion: v1
version: 0.7.0-1
description: mariadb-svc subservice layer
name: mariadb-svc
keywords:
  - openstack
  - mariadb
  - mariadb-svc
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
