apiVersion: v1
version: 3.0.0 
description: openvswitch-ovsdb specific layer
name: openvswitch-ovsdb
keywords:
  - openstack
  - openvswitch-ovsdb
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
