global:
    kolla:
        all:
            kubernetes_entrypoint: true
        horizon:
            deployment:
                kubernetes_entrypoint: true
                dependencies:
                    service:
                    - horizon

