apiVersion: v1
version: 0.7.0-1
description: memcached-svc subservice layer
name: memcached-svc
keywords:
  - openstack
  - memcached
  - memcached-svc
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
