name: ironic-inspector-create-keystone-endpoint-internal-job
version: 0.7.0-1
description: Helm chart for the ironic inspector internal keystone endpoint
keywords:
  - openstack
  - ironic
  - inspector
  - keystone-endpoint-internal
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
