{{- $searchPath := ":global.kolla.nova.placement_api.delete_keystone_service.job:global.kolla.nova.placement_api.delete_keystone_service.all:global.kolla.nova.placement_api.all:global.nova.kolla.all:global.kolla.all" }}
{{- $resourceName := "nova-placement-api-delete-keystone-service" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- $serviceName := "placement-api" }}
{{- $serviceType := "placement" }}
{{- $description := "Placement Service" }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "description" $description "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_delete_keystone_service" $env }}
{{- end }}
