{{- $mariadbImageBuilt := printf "%s/%s/%s-%s-mariadb:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.mariadb_image_tag | default .Values.kolla_tag }}
{{- $mariadbImageFull := .Values.mariadb_image_full | default $mariadbImageBuilt }}
{{- $resourceName := "mariadb-bootstrap" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "Values" .Values "Release" .Release }}
apiVersion: batch/v1
kind: Job
spec:
  template:
{{- include "init_container_header" . | indent 4 }}
{{- include "common_dependency_container_single" . | indent 10 }}
{{- include "init_container_tail" . | indent 8 }}
    spec:
      nodeSelector:
          {{ .Values.selector_key }}: {{ .Values.selector_value | quote }}
      containers:
        - image: "{{ $mariadbImageFull }}"
          name: main
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
            - mountPath: {{ .Values.container_config_directory }}
              name: mariadb-config
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
          env:
{{- include "common_bootstrap_env_vars" . | indent 12 }}
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: password
      volumes:
{{- include "common_volumes" . | indent 8 }}
        - name: mariadb-config
          configMap:
            name: {{ .Values.element_name }}
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.element_name }}
      restartPolicy: OnFailure
metadata:
  name: {{ .Values.element_name }}-bootstrap
{{- end }}
