name: ironic-api-delete-db-job
version: 0.7.0-1
description: Helm chart to delete the ironic database
keywords:
  - openstack
  - ironic
  - api
  - delete
  - database
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
