{{- $resourceName := "cinder" }}
{{- $serviceName := "cinder" }}
{{- $podTypeBootstrap := true }}
{{- with $env := dict "resourceName" $resourceName "serviceName" $serviceName "podTypeBootstrap" $podTypeBootstrap "Values" .Values "Release" .Release }}
{{- include "common_create_db_job" $env }}
        - name: cinder-api-config
          configMap:
            name: cinder-api
{{- end }}
