name: ironic-api-create-keystone-endpoint-public-job
version: 0.7.0-1
description: Helm chart for creating ironic api public keystone endpoint
keywords:
  - openstack
  - ironic
  - api
  - keystone-endpoint-admin
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
