apiVersion: v1
version: 0.7.0-1
description: mariadb-statefulset subservice layer
name: mariadb-statefulset
keywords:
  - openstack
  - mariadb
  - mariadb-statefulset
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
