dependencies:
  - name: neutron-create-db-job
    repository: file://../../microservice/neutron-create-db-job
    version: 0.7.0-1
  - name: neutron-server-svc
    repository: file://../../microservice/neutron-server-svc
    version: 0.7.0-1
  - name: neutron-create-keystone-service-job
    repository: file://../../microservice/neutron-create-keystone-service-job
    version: 0.7.0-1
  - name: neutron-create-keystone-endpoint-admin-job
    repository: file://../../microservice/neutron-create-keystone-endpoint-admin-job
    version: 0.7.0-1
  - name: neutron-create-keystone-endpoint-internal-job
    repository: file://../../microservice/neutron-create-keystone-endpoint-internal-job
    version: 0.7.0-1
  - name: neutron-create-keystone-endpoint-public-job
    repository: file://../../microservice/neutron-create-keystone-endpoint-public-job
    version: 0.7.0-1
  - name: neutron-create-keystone-user-job
    repository: file://../../microservice/neutron-create-keystone-user-job
    version: 0.7.0-1
  - name: neutron-manage-db-job
    repository: file://../../microservice/neutron-manage-db-job
    version: 0.7.0-1
  - name: neutron-server-deployment
    repository: file://../../microservice/neutron-server-deployment
    version: 0.7.0-1
  - name: neutron-dhcp-agent-daemonset
    repository: file://../../microservice/neutron-dhcp-agent-daemonset
    version: 0.7.0-1
  - name: neutron-l3-agent-daemonset
    repository: file://../../microservice/neutron-l3-agent-daemonset
    version: 0.7.0-1
  - name: neutron-metadata-agent-daemonset
    repository: file://../../microservice/neutron-metadata-agent-daemonset
    version: 0.7.0-1
  - name: neutron-openvswitch-agent-network-daemonset
    repository: file://../../microservice/neutron-openvswitch-agent-network-daemonset
    version: 0.7.0-1
  - name: neutron-openvswitch-agent-compute-daemonset
    repository: file://../../microservice/neutron-openvswitch-agent-compute-daemonset
    version: 0.7.0-1
    condition: global.kolla.all.multi_node
