{{- $searchPath := ":global.kolla.nova.placement_api.create_keystone_endpoint.public.job:global.kolla.nova.placement_api.create_keystone_endpoint.all:global.kolla.nova.placement_api.all:global.kolla.nova.all:global.kolla.all" }}
{{- $resourceName := "placement-create-keystone-endpoint-public" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := true }}
{{- $serviceName := "placement-api" }}
{{- $serviceType := "placement" }}
{{- $interface := "public" }}
{{- $port := include "kolla_val_get_str" (dict "key" "port" "searchPath" $searchPath "Values" .Values) }}
{{- $externalVip := include "kolla_val_get_str" (dict "key" "external_vip" "searchPath" $searchPath "Values" .Values) }}
{{- $placementapiPublicEndpointBuilt := printf "http://%s:%s" $externalVip $port }}
{{- $endpointURLFullUser := include "kolla_val_get_str" (dict "key" "endpoint" "searchPath" $searchPath "Values" .Values) }}
{{- $endpointURLFull := $endpointURLFullUser | default $placementapiPublicEndpointBuilt }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "interface" $interface "endpointURLFull" $endpointURLFull "Release" .Release "Values" .Values "searchPath" $searchPath }}
{{- include "common_create_keystone_endpoint" $env }}
{{- end }}
