apiVersion: v1
version: 0.7.0-1
description: rabbitmq-init-element subservice layer
name: rabbitmq-init-element-job
keywords:
  - openstack
  - rabbitmq
  - rabbitmq-init-element
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
