dependencies:
  - name: neutron-delete-db-job
    repository: file://../../microservice/neutron-delete-db-job
    version: 0.7.0-1
  - name: neutron-delete-keystone-service-job
    repository: file://../../microservice/neutron-delete-keystone-service-job
    version: 0.7.0-1
  - name: neutron-delete-keystone-user-job
    repository: file://../../microservice/neutron-delete-keystone-user-job
    version: 0.7.0-1
