{{- $dhcpAgentImageBuilt := printf "%s/%s/%s-%s-neutron-dhcp-agent:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.metadata_agent_image_tag }}
{{- $dhcpAgentImageFull := .Values.dhcp_agent_image_full | default $dhcpAgentImageBuilt }}

{{- $resourceName := printf "neutron-dhcp-agent-%s" $restype }}
{{- $netHostTrue := true }}
{{- $podTypeBootstrap := false }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" false "resourceName" $resourceName "Values" .Values }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-dhcp-agent
  labels:
    component: neutron
    system: dhcp-agent
spec:
  template:
    metadata:
      labels:
        component: neutron
        system: dhcp-agent
      annotations:
#FIXME Its unclear if ovsdb_connection, local_ip, and/or hostPID required. Try removing them once we have a working gate to test with.
#FIXME Once out of alpha, this should be converted to yaml.
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "update-config",
                "image": {{ include "kolla_toolbox_image_full" $env | quote }},
                "imagePullPolicy": {{ .Values.image_pull_policy | quote }},
                "command": [
                    "/bin/sh",
                    "-c",
                    "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
{{- if enable_openvswitch_tcp -}}
                    TUNNEL_INTERFACE={{ .Values.tunnel_interface }};
                    F=/var/lib/kolla-kubernetes/neutron-openvswitch-agent/tunnel_interface;
                    [ -f $F ] && TUNNEL_INTERFACE=$(<$F);
                    IP=$(ip addr list \"$TUNNEL_INTERFACE\" | grep ''inet '' |cut -d'' '' -f6|cut -d/ -f1);
                    crudini --set /srv/pod-main-config/ml2_conf.ini ovs ovsdb_connection tcp:$IP:6640;
{{- end -}}
                    crudini --set /srv/pod-main-config/ml2_conf.ini ovs local_ip $IP;
                "],
                "volumeMounts": [
                    {
                        "name": "neutron-dhcp-agent-configmap",
                        "mountPath": "/srv/configmap"
                    },
                    {
                        "name": "pod-main-config",
                        "mountPath": "/srv/pod-main-config"
                    }
                ]
            },
            {
                "name": "update-permissions",
                "image": {{ $dhcpAgentImageFull | quote }},
                "imagePullPolicy": {{ .Values.image_pull_policy | quote }},
                "securityContext": {
                    "runAsUser": 0
                },
                "command": [
                    "/bin/sh",
                    "-c",
                    "chown --recursive neutron.kolla /var/log/kolla;"
                ],
                "volumeMounts": [
                    {
                        "name": "kolla-logs",
                        "mountPath": "/var/log/kolla"
                    }
                ]
            }
        ]'
    spec:
      hostNetwork: True
      hostIPC: True
      hostPID: True
      nodeSelector:
        {{ selector.key }}: {{ selector.value }}
      containers:
        - image: "{{ neutron_dhcp_agent_image_full }}"
          name: main
          securityContext:
            privileged: true
          volumeMounts:
{{ include "common_volume_mounts" | indent 12 }}
            - mountPath: {{ .Values.container_config_directory }}
              name: pod-main-config
              readOnly: true
            - mountPath: /var/lib/neutron/kolla/
              name: neutron-metadata-socket
            - mountPath: /var/run
              name: host-run
            - mountPath: /run/netns/
              name: host-run-netns
              # shared: true # This seems not support in K8s yet :(
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
      volumes:
{{ include "common_volumes" $env | indent 8 }}
        - name: pod-main-config
          emptyDir: {}
        - name: neutron-dhcp-agent-configmap
          configMap:
            name: neutron-dhcp-agent
            items:
            - key: neutron.conf
              path: neutron.conf
            - key: config.json
              path: config.json
            - key: ml2-conf.ini
              path: ml2_conf.ini
            - key: dhcp-agent.ini
              path: dhcp_agent.ini
            - key: dnsmasq.conf
              path: dnsmasq.conf
        - name: host-run-netns
          hostPath:
            path: /run/netns
        - name: host-run
          hostPath:
            path: /var/run
        - name: neutron-metadata-socket
          hostPath:
            path: /var/lib/neutron/kolla/metadata_proxy
