{{- $searchPath := ":global.kolla.nova.placement_api.deployment:global.kolla.nova.placement_api.all:global.kolla.nova.all:global.kolla.all" }}
{{- $c := dict "searchPath" $searchPath "Values" .Values }}
{{- $_ := set $c "contName" "nova-placement-api" }}
{{- $_ := set $c "imageName" "image_full" }}
{{- $_ := set $c "tagName" "image_tag" }}
{{- $imageFull := include "kolla_build_image_full" $c }}
{{- $imagePullPolicy := include "kolla_val_get_str" (dict "key" "image_pull_policy" "searchPath" $searchPath "Values" .Values ) }}
{{- $resourceName := "placement-api" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "nova-placement" }}
{{- $serviceType := "api" }}
{{- $configFileName := "nova.conf" }}
{{- $configSectionName := "DEFAULT" }}
{{- $configListenHostParameter := "osapi_compute_listen" }}
{{- $configListenPortParameter := "osapi_compute_listen_port" }}
{{- $portName := "placement-api" }}
{{- $initContainers := "placement_api_initcontainer" }}
{{- $checkPath := "/" }}
{{- $privileged := false }}
{{- $haproxy := true }}
{{- define "placement_api_initcontainer" }}
- name: initialize-placement-api-logs
  image: {{ .imageFull | quote }}
  imagePullPolicy: {{ .imagePullPolicy | quote }}
  command:
    - sh
    - -ce
    - |
      mkdir -p /var/log/kolla/nova;
      chown -R keystone: /var/log/kolla/nova;
      chmod 755 /var/log/kolla/nova;
  volumeMounts:
    - name: kolla-logs
      mountPath: /var/log/kolla
{{- end }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "configFileName" $configFileName "configSectionName" $configSectionName "configListenHostParameter" $configListenHostParameter "configListenPortParameter" $configListenPortParameter "portName" $portName "imageFull" $imageFull "imagePullPolicy" $imagePullPolicy "checkPath" $checkPath "initContainers" $initContainers "privileged" $privileged "haproxy" $haproxy "Values" .Values "Release" .Release "searchPath" $searchPath }}
{{- include "common_api_python_deployment" $env }}
{{- end }}
