apiVersion: v1
version: 0.7.0-1
description: rabbitmq-svc subservice layer
name: rabbitmq-svc
keywords:
  - openstack
  - rabbitmq
  - rabbitmq-svc
home: http://www.openstack.org
sources:
  - http://github.com/openstack
engine: gotpl
