name: nova-api-create-simple-cell-job
version: 0.7.0-1
description: nova api job to create a simple cell
keywords:
  - openstack
  - nova
  - api
  - cell
  - simple
  - create
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
