{{- $imageBuilt := printf "%s/%s/%s-%s-cinder-volume-ceph:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.image_tag }}
{{- $imageFull := .Values.image_full | default $imageBuilt }}
{{- $resourceName := "cinder-volume-ceph" }}
{{- $netHostTrue := false }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "cinder" }}
{{- $serviceType := "volume" }}
{{- $privileged := true }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "imageFull" $imageFull "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "privileged" $privileged "Values" .Values }}
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: {{ .Values.element_name }}
  labels:
    component: {{ $resourceName }}
    system:  {{ .Values.element_name }}
spec:
  serviceName: {{ $serviceName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        component: {{ $resourceName }}
        system: {{ .Values.element_name }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
          {
             "name": "initialize-config",
             "image": {{ include "kolla_toolbox_image_full" . | quote }},
             "command": [
                 "bash",
                 "-ec",
                 "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
                  cp -a /srv/ceph.conf /srv/pod-main-config/;
                  cp -a /srv/ceph.client.cinder.keyring /srv/pod-main-config/;
             "],
             "volumeMounts": [
                {
                    "name": "ceph-conf",
                    "mountPath": "/srv/ceph.conf",
                    "subPath": "ceph.conf"
                },
                {
                    "name": "ceph-client-cinder-keyring",
                    "mountPath": "/srv/ceph.client.cinder.keyring",
                    "subPath": "ceph.client.cinder.keyring"
                },
                {
                   "name": "cinder-volume-configmap",
                   "mountPath": "/srv/configmap"
                },
                {
                   "name": "pod-main-config",
                   "mountPath": "/srv/pod-main-config"
                }
             ]
          },
          {
             "name": "initialize-cinder-logs",
             "image": "{{ $imageFull }}",
             "command": [
                 "sh",
                 "-ce",
                 "mkdir /var/log/kolla/cinder ;
                  chown -R cinder: /var/log/kolla/cinder "],
             "volumeMounts": [
                {
                   "name": "kolla-logs",
                   "mountPath": "/var/log/kolla"
                }
             ]
          }
        ]'
    spec:
      hostPID: True
      nodeSelector:
          {{ .Values.selector_key }}: {{ .Values.selector_value | quote }}
      containers:
        - image: "{{ $imageFull }}"
          name: main
          env:
{{- include "common_env_vars" $env | indent 12 }}
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
            - mountPath: {{ .Values.container_config_directory }}
              name: pod-main-config
              readOnly: true
{{- include "common_containers" $env | indent 8 }}
      volumes:
{{- include "common_volumes" $env | indent 8 }}
        - name: pod-main-config
          emptyDir: {}
        - name: cinder-volume-configmap
          configMap:
            name: cinder-volume
        - name: ceph-conf
          configMap:
            name: ceph-conf
        - name: ceph-client-cinder-keyring
          secret:
            secretName: ceph-client-cinder-keyring
{{- end }}
