name: glance-delete-keystone-user-job
version: 0.7.0-1
description: Helm chart to delete the glance keystone user
keywords:
  - openstack
  - glance
  - delete
  - user
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
