---
- name: Generate configuration files
  hosts: localhost
  connection: local
  roles:
    - rabbitmq
    - mariadb
    - nova
    - neutron
    - keystone
    - glance
    - horizon
    - memcached
    - cinder
    - heat
    - ironic
