name: compute-kit
version: 0.7.0-1
description: Helm chart for openstack compute kit deployment
keywords:
  - openstack
  - mariadb
  - rabbitmq
  - memcached
  - openvswitch
  - keystone
  - glance
  - neutron
  - cinder-control
  - cinder-volume-ceph
  - nova-control
  - nova-compute
  - horizon
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
