common:
        selector_key: kolla_controller
        selector_value: "true"

        docker_registry: docker.io
        docker_namespace: kolla
        kolla_base_distro: centos
        kolla_install_type: binary

        image_pull_policy: IfNotPresent

        enable_resolve_conf_net_host_workaround: true
        enable_openvswitch_tcp: false
        enable_neutron_dvr: false

        container_config_directory: /var/lib/kolla/config_files

        #Common Image overrides
        #fluentd_image_full:
        #kolla_toolbox_image_tag:

        enable_kube_logger: true
        fluentd_image_tag: 3.0.1
        kolla_toolbox_image_tag: 3.0.1
        kubernetes_entrypoint_image_tag: 3.0.1

common-create-keystone-admin:
        keystone_admin_protocol: http
        keystone_admin_svcname: keystone-admin
        keystone_admin_port: 35357
        keystone_admin_url:
        keystone_admin_project: admin
        keystone_admin_username: admin
        keystone_admin_domain_name: Default
        region: RegionOne

pod-http-termination:
        haproxy_python_termination: true
        haproxy_image_tag: 2.0.2

stateful-service:
        storage_provider: "host"
        storage_provider_fstype: "xfs"
        ceph:
               monitors: []
               pool: kollavolumes
               secret_name: ceph-kolla
               user: kolla

openvswitch-ovsdb:
        openvswitch_ovsdb_image_tag: 2.0.2

keystone-admin-svc:
        port: 35357

keystone-internal-svc:
        port: 5000

keystone-public-svc:
        port: 5000

keystone-create-db:
        database_host: "mariadb"
        database_port: 3306
        database_name: "keystone"
        database_user: "keystone"

keystone-manage-db:
        image_tag: 2.0.2

keystone-create-endpoints:
        image_tag: 2.0.2
        port: 5000
        admin_port: 35357
        region: RegionOne

neutron-create-keystone-endpoint-public:
        kolla_kubernetes_external_vip:
        neutron_server_port: 9696

neutron-create-keystone-endpoint-internal:
        neutron_internal_service: neutron-server
        neutron_server_port: 9696

neutron-create-keystone-endpoint-admin:
        neutron_admin_service: neutron-server
        neutron_server_port: 9696

neutron-server:
        image_tag: 2.0.2
        replicas: 3
        port: 9696

neutron-openvswitch-agent:
        type: network

        #Image overrides
        #openvswitch_agent_image_full:
        openvswitch_agent_image_tag: 2.0.2

        logger_configmap_name: neutron-openvswitch-agent-logger

        tunnel_interface: eth0

neutron-l3-agent:
        type: network

        #Image overrides
        #l3_agent_image_full:
        l3_agent_image_tag: 2.0.2

        logger_configmap_name: neutron-l3-agent-logger

        tunnel_interface: eth0

openvswitch-vswitchd:
        openvswitch_vswitchd_image_tag: 2.0.2
        kolla_kubernetes_ovs_setup_bridge: true
        kolla_kubernetes_ovs_add_port: false
        ext_bridge_name: "br-ex"
        ext_interface_name: "eth1"

rabbitmq-init-element:
        rabbitmq_cluster_cookie:
        rabbitmq_image_tag: 3.0.1

rabbitmq-pod:
        rabbitmq_port: 5672
        rabbitmq_management_port: 15672
        rabbitmq_image_tag: 3.0.1

rabbitmq-pv:
        rabbitmq_volume_size_gb: 10

rabbitmq-pvc:
        rabbitmq_volume_size_gb: 10

rabbitmq-svc:
        rabbitmq_port: 5672
        rabbitmq_management_port: 15672

memcached:
        memcached_replicas: 1
        memcached_port: 11211
        memcached_image_tag: 3.0.1

mariadb-init-element:
        mariadb_image_tag: 3.0.1

mariadb-pod:
        database_user: root
        mariadb_port: 3306
        mariadb_image_tag: 3.0.1

mariadb-pv:
        mariadb_volume_size_gb: 10

mariadb-pvc:
        mariadb_volume_size_gb: 10

mariadb-svc:
        mariadb_port: 3306

nova-api-svc:
        port: 8774

nova-metadata-svc:
        port: 8775

nova-novncproxy-svc:
        port: 6080

nova-create-db:
        database_host: "mariadb"
        database_port: 3306
        database_name: "nova"
        database_user: "nova"

nova-api-create-db:
        database_host: "mariadb"
        database_port: 3306
        database_name: "nova_api"
        database_user: "nova_api"

nova-api-manage-db:
        image_tag: 2.0.2

nova-api:
        image_tag: 2.0.2
        replicas: 3
        port: 8774
        metadata_port: 8775

nova-conductor:
        image_tag: 2.0.2
        replicas: 1

nova-scheduler:
        image_tag: 2.0.2
        replicas: 1

nova-consoleauth:
        image_tag: 2.0.2
        replicas: 1

nova-novncproxy:
        image_tag: 2.0.2
        replicas: 1
        port: 6080

nova-compute:
        image_tag: 2.0.2
        selector_key: kolla_compute
        selector_value: "true"
        libvirt_tcp: false
        nova_ceph: true

nova-libvirt:
        image_tag: 2.0.2
        selector_key: kolla_compute
        selector_value: "true"
        libvirt_tcp: false
        libvirt_ceph: true

glance-pv:
        glance_volume_size_gb: 10

glance-pvc:
        glance_volume_size_gb: 10

heat-api:
        image_tag: 3.0.1
        replicas: 1
        port: 8004

heat-api-cfn:
        image_tag: 3.0.1
        replicas: 1
        port: 8000

heat-engine:
        image_tag: 3.0.1
        replicas: 1

glance-api-svc:
        glance_api_port: 9292
        type: "api"

glance-registry-svc:
        glance_registry_port: 9191
        type: "registry"

cinder-create-db:
        database_host: "mariadb"
        database_port: 3306
        database_name: "cinder"
        database_user: "cinder"

cinder-manage-db:
        image_tag: 2.0.2

cinder-api-svc:
        port: 8776

horizon-api:
        horizon_image_tag: 2.0.2
        replicas: 1
        port: 80

horizon-svc:
        type: dashboard
        port: 80

cinder-create-keystone-endpoint-admin:
        cinder_admin_service: cinder-api
        cinder_api_port: 8776

cinder-create-keystone-endpoint-adminv2:
        cinder_admin_service: cinder-api
        cinder_api_port: 8776

cinder-create-keystone-endpoint-public:
        kolla_kubernetes_external_vip:
        cinder_api_port: 8776

cinder-create-keystone-endpoint-publicv2:
        kolla_kubernetes_external_vip:
        cinder_api_port: 8776

cinder-create-keystone-endpoint-internal:
        cinder_internal_service: cinder-api
        cinder_api_port: 8776

cinder-create-keystone-endpoint-internalv2:
        cinder_internal_service: cinder-api
        cinder_api_port: 8776
