dependencies:
  - name: nova-api-svc
    repository: file://../../microservice/nova-api-svc
    version: 0.6.0-1
  - name: nova-metadata-svc
    repository: file://../../microservice/nova-metadata-svc
    version: 0.6.0-1
  - name: nova-novncproxy-svc
    repository: file://../../microservice/nova-novncproxy-svc
    version: 0.6.0-1
  - name: nova-create-keystone-service-job
    repository: file://../../microservice/nova-create-keystone-service-job
    version: 0.6.0-1
  - name: nova-create-keystone-user-job
    repository: file://../../microservice/nova-create-keystone-user-job
    version: 0.6.0-1
  - name: nova-create-keystone-endpoint-admin-job
    repository: file://../../microservice/nova-create-keystone-endpoint-admin-job
    version: 0.6.0-1
  - name: nova-create-keystone-endpoint-internal-job
    repository: file://../../microservice/nova-create-keystone-endpoint-internal-job
    version: 0.6.0-1
  - name: nova-create-keystone-endpoint-public-job
    repository: file://../../microservice/nova-create-keystone-endpoint-public-job
    version: 0.6.0-1
  - name: nova-create-db-job
    repository: file://../../microservice/nova-create-db-job
    version: 0.6.0-1
  - name: nova-api-create-db-job
    repository: file://../../microservice/nova-api-create-db-job
    version: 0.6.0-1
  - name: nova-api-manage-db-job
    repository: file://../../microservice/nova-api-manage-db-job
    version: 0.6.0-1
  - name: nova-api-deployment
    repository: file://../../microservice/nova-api-deployment
    version: 0.6.0-1
  - name: nova-conductor-statefulset
    repository: file://../../microservice/nova-conductor-statefulset
    version: 0.6.0-1
  - name: nova-scheduler-statefulset
    repository: file://../../microservice/nova-scheduler-statefulset
    version: 0.6.0-1
  - name: nova-consoleauth-statefulset
    repository: file://../../microservice/nova-consoleauth-statefulset
    version: 0.6.0-1
  - name: nova-novncproxy-deployment
    repository: file://../../microservice/nova-novncproxy-deployment
    version: 0.6.0-1
  - name: nova-placement-deployment
    repository: file://../../microservice/nova-placement-deployment
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
  - name: nova-placement-create-keystone-user-job
    repository: file://../../microservice/nova-placement-create-keystone-user-job
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
  - name: nova-placement-create-keystone-service-job
    repository: file://../../microservice/nova-placement-create-keystone-service-job
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
  - name: nova-placement-create-keystone-endpoint-internal-job
    repository: file://../../microservice/nova-placement-create-keystone-endpoint-internal-job
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
  - name: nova-placement-create-keystone-endpoint-admin-job
    repository: file://../../microservice/nova-placement-create-keystone-endpoint-admin-job
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
  - name: nova-placement-create-keystone-endpoint-public-job
    repository: file://../../microservice/nova-placement-create-keystone-endpoint-public-job
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
  - name: nova-placement-svc
    repository: file://../../microservice/nova-placement-svc
    version: 0.6.0-1
    condition: global.kolla.nova.all.placement_api_enabled
