{{- $imageBuilt := printf "%s/%s/%s-%s-cinder-volume:%s" .Values.docker_registry .Values.docker_namespace .Values.kolla_base_distro .Values.kolla_install_type .Values.image_tag }}
{{- $imageFull := .Values.image_full | default $imageBuilt }}
{{- $resourceName := "cinder-volume-lvm" }}
{{- $netHostTrue := true }}
{{- $podTypeBootstrap := false }}
{{- $serviceName := "cinder" }}
{{- $serviceType := "volume" }}
{{- $privileged := true }}
{{- with $env := dict "netHostTrue" $netHostTrue "podTypeBootstrap" $podTypeBootstrap "imageFull" $imageFull "resourceName" $resourceName "serviceName" $serviceName "serviceType" $serviceType "privileged" $privileged "Values" .Values "Release" .Release }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Values.element_name }}
  labels:
    component: {{ $resourceName }}
    system:  {{ .Values.element_name }}
spec:
  template:
    metadata:
      labels:
        component: {{ $resourceName }}
        system: {{ .Values.element_name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
             "name": "initialize-cinder-volume-lvm",
             "image": {{ include "kolla_toolbox_image_full" . | quote }},
             "imagePullPolicy": {{ .Values.image_pull_policy | quote }},
             "command": [
                 "bash",
                 "-ce",
                 "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
                  {{- $map := index .Values "lvm_backends" }}
                  {{- range $key, $val := $map }}
                  {{- range $key2, $val2 := $val }}
                  {{ $vg_ip := $key2 }}
                  {{ $vg_name := $val2 }}
                  {{ $lvm_enabled_backend := printf "%s_%s" $vg_ip $vg_name }}
                     crudini --set /srv/pod-main-config/cinder.conf DEFAULT enabled_backends {{ $lvm_enabled_backend }};
                     crudini --set /srv/pod-main-config/cinder.conf {{ $lvm_enabled_backend }} volume_group {{ $vg_name }};
                     crudini --set /srv/pod-main-config/cinder.conf {{ $lvm_enabled_backend }} volume_backend_name {{ $lvm_enabled_backend }};
                     crudini --set /srv/pod-main-config/cinder.conf {{ $lvm_enabled_backend }} volume_driver  ''cinder.volume.drivers.lvm.LVMVolumeDriver'';
                     crudini --set /srv/pod-main-config/cinder.conf {{ $lvm_enabled_backend }} iscsi_helper  ''tgtadm'';
                     crudini --set /srv/pod-main-config/cinder.conf {{ $lvm_enabled_backend }} iscsi_protocol  ''iscsi'';
                     crudini --set /srv/pod-main-config/cinder.conf {{ $lvm_enabled_backend }} iscsi_ip_address {{ $vg_ip }};
                  {{- end }}
                  {{- end }} "],
             "volumeMounts": [
                {
                   "name": "cinder-volume-configmap",
                   "mountPath": "/srv/configmap"
                },
                {
                   "name": "pod-main-config",
                   "mountPath": "/srv/pod-main-config"
                }
             ]
          },
          {
             "name": "initialize-cinder-logs",
             "image": "{{ $imageFull }}",
             "imagePullPolicy": {{ .Values.image_pull_policy | quote }},
             "command": [
                 "sh",
                 "-ce",
                 "mkdir /var/log/kolla/cinder ;
                  chown -R cinder: /var/log/kolla/cinder "],
             "volumeMounts": [
                {
                   "name": "kolla-logs",
                   "mountPath": "/var/log/kolla"
                }
             ]
          }
        ]'
    spec:
      hostNetwork: True
      hostIPC: True
      nodeSelector:
          {{ .Values.selector_key }}: {{ .Values.selector_value | quote }}
      containers:
        - image: "{{ $imageFull }}"
          name: main
          securityContext:
            privileged: true
          env:
{{- include "common_env_vars" $env | indent 12 }}
          volumeMounts:
{{- include "common_volume_mounts" $env | indent 12 }}
            - mountPath: {{ .Values.container_config_directory }}
              name: pod-main-config
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /dev
              name: dev
            - mountPath: /sys/fs/cgroup
              name: sys-fs-cgroup
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /var/lib/cinder
              name: cinder-volumes
            - mountPath: /etc/iscsi
              name: iscsi-info
{{- include "common_containers" . | indent 8 }}
      volumes:
{{- include "common_volumes" . | indent 8 }}
        - name: pod-main-config
          emptyDir: {}
        - name: cinder-volume-configmap
          configMap:
            name: {{ .Values.element_name }}
        - name: cinder-volumes
          hostPath:
            path: /var/lib/cinder
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: iscsi-info
          hostPath:
            path: /etc/iscsi
{{- end }}
