name: ironic-api-svc
version: 0.7.0-1
description: ironic api svc microservice package
keywords:
  - openstack
  - ironic
  - api
  - svc
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
