name: heat-api-deployment
version: 0.7.0-1 #FIXME make this changable
description: Heat-api service for kolla-kubernetes
keywords:
  - openstack
  - heat
  - heat-api
sources:
  - http://github.com/openstack
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional). make this point to the new project icons when ready
